Don't mix tab and spaces indentation in pre-commit hook (#1)

diff --git a/tools/githook/pre-commit b/tools/githook/pre-commit
--- a/tools/githook/pre-commit
+++ b/tools/githook/pre-commit
@@ -1,33 +1,30 @@
 #!/bin/sh
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
+if git rev-parse --verify HEAD >/dev/null 2>&1; then
+    against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    # Initial commit: diff against an empty tree object
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
-FILES=$(git diff-index --name-only --diff-filter=ACMR --cached $against -- |egrep ".py$")
+FILES=$(git diff-index --name-only --diff-filter=ACMR --cached $against -- | egrep ".py$")
 if [ "$FILES" != "" ]; then
     # We want to look at the staged version only, so we have to run it once for
     # each file.
     E=0
     for F in ${FILES}; do
+        if ! git show ":$F" | ruff check - --quiet --stdin-filename "$F"; then
+            E=1
+        fi
 
-	if ! git show ":$F" | ruff check - --quiet --stdin-filename "$F"; then
-	    E=1
-	fi
-
-	if ! git show ":$F" | ruff format - --quiet --check; then
-	    E=1
-	    echo "Formatting errors in $F, run 'make format'"
-	fi
+        if ! git show ":$F" | ruff format - --quiet --check; then
+            E=1
+            echo "Formatting errors in $F, run 'make format'"
+        fi
     done
     if [ "$E" != "0" ]; then
-	exit 1
+        exit 1
     fi
 
     echo Basic python checks passed.
 fi
-
